set(CPACK_PACKAGE_VERSION ${VERSION})
set(CPACK_GENERATOR "RPM")
set(CPACK_PACKAGE_NAME "CepGen")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A generic central exclusive processes event generator")
set(CPACK_PACKAGE_RELEASE 1)
set(CPACK_PACKAGE_CONTACT "Laurent Forthomme <cepgen@projects.hepforge.org>")
set(CPACK_PACKAGE_VENDOR "Helsinki Institute of Physics")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/CepGen/README")
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_PACKAGE_RELEASE}.${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
#--- register packages
set(CPACK_COMPONENTS_ALL lib devel boost)
set(CPACK_COMPONENT_lib_DISPLAY_NAME "CepGen core library")
set(CPACK_COMPONENT_lib_DESCRIPTION "The full set of core libraries embedded within CepGen")
set(CPACK_COMPONENT_devel_DISPLAY_NAME "CepGen development headers")
set(CPACK_COMPONENT_devel_DESCRIPTION "A set of C and C++ includes for the development of CepGen-dependent libraries")
set(CPACK_COMPONENT_boost_DISPLAY_NAME "CepGen Boost wrappers library")
set(CPACK_COMPONENT_boost_DESCRIPTION "A collection of wrappers to the Boost library")
set(CPACK_COMPONENT_INSTALL ON)
#--- interdependency between packages
set(CPACK_COMPONENT_devel DEPENDS lib)
set(CPACK_COMPONENT_boost DEPENDS lib)
#--- RPM information
set(CPACK_RPM_MAIN_COMPONENT lib)
set(CPACK_RPM_FILE_NAME RPM-DEFAULT)
set(CPACK_RPM_devel_PACKAGE_ARCHITECTURE noarch)
set(CPACK_RPM_PACKAGE_LICENSE GPL3+)
set(CPACK_RPM_CHANGELOG_FILE "${CMAKE_CURRENT_SOURCE_DIR}/CHANGELOG")
set(CPACK_RPM_PACKAGE_URL https://cepgen.hepforge.org/)
set(CPACK_RPM_PACKAGE_AUTOREQPROV " no")
list(APPEND CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST /usr/lib)
list(APPEND CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST /usr/include)
list(APPEND CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST /usr/local/lib)
list(APPEND CPACK_RPM_EXCLUDE_FROM_AUTO_FILELIST /usr/local/include)
include(CPack)
