macro(cepgen_build mod_name)
    set(options)
    set(one_val)
    set(multi_vals SOURCES EXT_LIBS EXT_HEADERS EXT_BINS DEPENDS DEFINITIONS PROPERTY INSTALL_COMPONENT)
    cmake_parse_arguments(ARG "${options}" "${one_val}" "${multi_vals}" ${ARGN})
    message(STATUS "Building ${mod_name} add-on")
    if(ARG_SOURCES)
        set(sources)
        foreach(_s ${ARG_SOURCES})
            file(GLOB s "${_s}")
            list(APPEND sources ${s})
        endforeach()
        add_library(${mod_name} SHARED ${sources})
        if(ARG_EXT_LIBS)
            message(STATUS "... external libraries: ${ARG_EXT_LIBS}")
            target_link_libraries(${mod_name} ${ARG_EXT_LIBS})
        endif()
        if(ARG_EXT_HEADERS)
            message(STATUS "... external headers: ${ARG_EXT_HEADERS}")
            target_include_directories(${mod_name} PRIVATE ${ARG_EXT_HEADERS})
        endif()
        if(ARG_DEPENDS)
            foreach(_dep ${ARG_DEPENDS})
                file(GLOB dep ${_dep})
                if(NOT dep)
                    message(FATAL_ERROR "Failed to locate ${_dep}!")
                endif()
            endforeach()
            message(STATUS "... external dependencies: ${ARG_DEPENDS}")
        endif()
        if(ARG_PROPERTY)
            set_property(TARGET ${mod_name} PROPERTY ${ARG_PROPERTY})
        endif()
        if(ARG_DEFINITIONS)
            target_compile_definitions(${mod_name} PRIVATE ${ARG_DEFINITIONS})
        endif()
        if(ARG_CFLAGS)
            message(STATUS "... compile flags: ${ARG_CFLAGS}")
            set_target_properties(${mod_name} PROPERTIES COMPILE_FLAGS ${ARG_CFLAGS})
        endif()
        list(APPEND CEPGEN_ADDONS_EXT ${mod_name})
    else() # interfacing library (only includes)
        add_library(${mod_name} INTERFACE)
    endif()
    target_include_directories(${mod_name} INTERFACE ${PROJECT_SOURCE_DIR})
    if(ARG_INSTALL_COMPONENT)
        #----- installation rules
        install(TARGETS ${mod_name}
            DESTINATION ${CMAKE_INSTALL_LIBDIR}
            COMPONENT ${ARG_INSTALL_COMPONENT})
        install(DIRECTORY
            DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}
            COMPONENT ${ARG_INSTALL_COMPONENTS}
            FILES_MATCHING PATTERN "*.h")
        file(APPEND ${CEPGEN_ADDONS_FILE} "${mod_name}\n")
    endif()
    set(CEPGEN_ADDONS_EXT ${CEPGEN_ADDONS_EXT} PARENT_SCOPE)
endmacro()
