name: Package

on:
  push:
    branches: ci-rpm_build  #FIXME to be switched to tag
  workflow_dispatch:
    secrets: inherit
    config-path: .github/labeler.yml

env:
  BUILD_TYPE: Release  # Release, Debug, RelWithDebInfo, etc
  CEPGEN_PATH: /Package/build
  CG_CI: True

jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: 'laufor/ci-images:cepgen-fedora39'
      options: -v ${{ github.workspace }}:/Package
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/workflows/build.yml
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Package
      run: cmake --build ${{env.CEPGEN_PATH}} --target package
